### ISSUE TITLE
App crashes on orientation change (NullPointerException: camera target is null)

### ISSUE THREAD

**Issue by dalmaracz** [HMS-Core/hms-mapkit-demo-java#3] opened 2020-07-02 09:42 UTC
Steps to reproduce:
1. Open demo app
2. On main page click on "Marker Demo" and rapidly rotate the screen (before map gets to be created on next screen, you have to almost simultaneously click on button and rotate the screen)
3. App crashes with following stack trace:

E/MarkerDemoActivity: NullPointerException java.lang.NullPointerException: camera target is null
2020-07-02 12:16:17.405 14733-14733/com.huawei.hms.maps.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.huawei.hms.maps.sample, PID: 14733
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.huawei.map.mapapi.HWMap.setDefaultLocationSource(com.huawei.map.mapapi.LocationSource)' on a null object reference
        at com.huawei.hms.maps.provider.huawei.e.a(:47579)
        at com.huawei.hms.maps.provider.huawei.e$14.b(:1519)
        at o.fa$3.run(Unknown Source:0)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
2020-07-02 12:16:17.406 14733-14733/com.huawei.hms.maps.sample E/HmsMapKit_CrashHandler_79: uncaughtException stacktrace is java.lang.NullPointerException: Attempt to invoke virtual method 'void com.huawei.map.mapapi.HWMap.setDefaultLocationSource(com.huawei.map.mapapi.LocationSource)' on a null object reference
        at com.huawei.hms.maps.provider.huawei.e.a(:47579)
        at com.huawei.hms.maps.provider.huawei.e$14.b(:1519)
        at o.fa$3.run(Unknown Source:0)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Note**: crash can be reproduced by clicking on other options/buttons from main screen not just "Marker Demo" button

**Comment by lovehuaweimaps** [comment] 2020-07-03 09:40
Hello! We can't reproduce this kind of scene now, can you provide the version number of the map sdk you use and the version number of the HMS Core APK, and can you provide the screen recording of the crash, we are not very clear about your steps. 
Thank you.

**Comment by dalmaracz** [comment] 2020-07-03 12:05
Hi!

HMS Core version is 5.0.0.302 (from logs: get athUrl success.athUrl is https://map-dre.platform.hicloud.com/map/v2/license/authenticate?clientVersion=50000302)

The app I'm testing is the Demo app from here so map sdk version is the one specified in gradle (implementation 'com.huawei.hms:maps:4.0.1.301')

I've uploaded 2 videos with the crash. In video1 it occurs only the second time I tap on Marker Demo button and rotate screen in video2 it happens from the first time. Reproduction steps: tap and Marker Demo button and simultaneously rotate device screen

video1: https://streamable.com/9tqha6
video2: https://streamable.com/pqx7en

**Comment by lovehuaweimaps** [comment] 2020-07-06 07:48
Thank you for your feedback. This issue will be resolved in HMS Core APK 5.0.1, the release time is about Mid-August. And we are looking at your other two issues with the same operations.

**Closed** 2020-07-14 09:34 UTC
